namespace Orikivo.Systems.Wrappers.Steam.Parameters
{
    public class SteamFullList
    {
       /*
         interval, string, false
         gamemode, string, false
         mapgroup, string, false
         event, uint32, false
         steamid, uint64, false
         steamidkey, string, false
         sectionid, uint32, false
         pickid0, uint32, false
         itemid0, uint64, false
         pickid1, uint32, false
         itemid1, uint64, false
         pickid2, uint32, false
         itemid2, uint64, false
         pickid3, uint32, false
         itemid3, uint64, false
         pickid4, uint32, false
         itemid4, uint64, false
         groupid, uint32, false
         index, uint32, false
         pickid, uint32, false
         itemid, uint64, false
         FantasyLeagueID, uint32, false
         StartTime, uint32, true
         EndTime, uint32, true
         matchid, uint64, true
         SeriesID, uint32, true
         PlayerAccountID, uint32, true
         accountid, uint32, false
         server_steam_id, uint64, false
         league_id, uint32, true
         match_id, uint64, true
         hero_id, uint32, true
         game_mode, uint32, true
         skill, uint32, true
         min_players, string, true
         account_id, string, true
         start_at_match_id, uint64, true
         matches_requested, string, true
         tournament_games_only, string, true
         start_at_match_seq_num, uint64, true
         start_at_team_id, uint64, true
         teams_requested, uint32, true
         partner, int32, false
         home_division, int32, true
         time_frame, string, true
         phase_id, uint32, true
         broadcaster_steam_id, uint64, false
         BadgeID, string, false
         ValidBadgeType1, uint32, false
         ValidBadgeType2, uint32, false
         ValidBadgeType3, uint32, false
         BadgeType, uint32, false
         eventid, uint32, false
         accountid, uint32, false
         language, string, true
         itemizedonly, bool, true
         iconname, string, false
         icontype, uint32, true
         leagueid, uint32, true
         class_id, uint32, false
         start, int32, true
         leaderboardName, string, false
         addr, string, false
         appid, uint32, false
         version, uint32, false
         key, string, false
         cdnname, string, false
         allowedipblocks, string, true
         allowedasns, string, true
         allowedipcountries, string, true
         mpbs_sent, uint32, true
         mbps_recv, uint32, true
         cpu_percent, uint32, true
         cache_hit_percent, uint32, true
         cellid, uint32, false
         maxcount, uint32, true
         class_count, uint32, false
         classid0, uint64, false
         instanceid0, uint64, true
         currency, string, true
         maxlength, uint32, true
         enddate, uint32, true
         feeds, string, true
         collectioncount, uint32, false
         publishedfileids[0], uint64, false
         itemcount, uint32, false
         ugcid, uint64, false
         relationship, string, true
         steamids, string, false
         vanityurl, string, false
         url_type, int32, true
         sessionkey, rawbinary, false
         encrypted_loginkey
         ticket, string, false
         access_token, string, false
         gameid, uint64, false
         name[0], string, false
         startdate, uint32, true
         l, string, true
         umqid, uint64, false
         message, uint32, false
         pollid, uint32, true
         sectimeout, uint32, true
         secidletime, uint32, true
         use_accountids, uint32, true
         promoid, uint32, false
         PromoID, uint32, false
         memo, string, false
         login_token, string, false
         server_ips, string, false
         server_steamids, uint64, false
         cache_id, uint32, false
         cache_key, string, false
         change_notes, string, false
         allowed_ip_blocks, string, false
         query_type, uint32, false
         page, uint32, false
         numperpage, uint32, true
         creator_appid, uint32, false
         requiredtags, string, false
         excludedtags, string, false
         match_all_tags, bool, true
         required_flags, string, false
         omitted_flags, string, false
         search_text, string, false
         filetype, uint32, false
         child_publishedfileid, uint64, false
         days, uint32, false
         include_recent_votes_only, bool, false
         cache_max_age_seconds, uint32, true
         required_kv_tags, {message}, false
         totalonly, bool, false
         ids_only, bool, false
         return_vote_data, bool, false
         return_tags, bool, false
         return_kv_tags, bool, false
         return_previews, bool, false
         return_children, bool, false
         return_short_description, bool, false
         return_for_sale_data, bool, false
         return_metadata, bool, true
         return_playtime_stats, uint32, false
         return_details, bool, false
         strip_description_bbcode, bool, false
         publishedfileids, uint64, false
         includetags, bool, false
         includeadditionalpreviews, bool, false
         includechildren, bool, false
         includekvtags, bool, false
         includevotes, bool, false
         short_description, bool, false
         includeforsaledata, bool, false
         includemetadata, bool, false
         type, string, true
         sortmethod, string, true
         privacy, uint32, false
         requiredtags, string, true
         excludedtags, string, false
         match_cloud_filename, string, false
         cache_max_age_seconds, uint32, true
         totalonly, bool, false
         ids_only, bool, false
         max_trades, uint32, false
         start_after_time, uint32, false
         start_after_tradeid, uint64, false
         navigating_back, bool, false
         get_descriptions, bool, false
         include_failed, bool, false
         include_total, bool, false
         tradeid, uint64, false
         get_description, bool, false
         get_sent_offers, bool, false
         get_received_offers, bool, false
         get_descriptions, bool, false
         active_only, bool, false
         historical_only, bool, false
         time_historical_cutoff, uint32, false
         tradeofferid, uint64, false
         time_last_visit, uint32, false
         steamid_target, uint64, false
         trade_offer_access_token, string, false
         ticket, string, false
         play_sessions, {message}, false
         include_appinfo, bool, false
         include_played_free_games, bool, false
         appids_filter, uint32, false
         badgeid, int32, false
         appid_playing, uint32, false
         context, uint64, false
         title, {message}, false
         users, {message}, false
         sessionid, uint64, false
         itemid, uint64, false
         quantity, uint32, false
         fromitemid, uint64, false
         destitemid, uint64, false
         ecurrency, int32, false
         if_modified_since, uint32, true
         have_description_language, string, true
         include_games, bool, true
         include_dlc, bool, true
         include_software, bool, true
         include_videos, bool, true
         include_hardware, bool, true
         last_appid, uint32, true
         max_results, uint32, true
         pathandfilename, string, false
         webcheaturl, string, false
         time_now, uint64, false
         time_started, uint64, false
         time_stopped, uint64, false
         cheatname, string, false
         game_process_id, uint32, false
         cheat_process_id, uint32, false
         cheat_param_1, uint64, false
         cheat_param_2, uint64, false

        216 different parameters in 55 services :^)
       */
    }
}